version: "3.9"
services:
  mongo-db:
    image: mongo
    container_name: mongo-service
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      metrics_internal:
        ipv4_address: 192.168.6.13
    ports:
      - "27017:27017"
    deploy:
      mode: host
  prometheus:
    image: my-prometheus
    container_name: prometheus
    networks:
      metrics_internal:
        ipv4_address: 192.168.6.10
    ports:
      - "60000:9090"
    deploy:
      mode: host
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger-all
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      metrics_internal:
        ipv4_address: 192.168.6.12
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    deploy:
      mode: host
  application:
    image: microservice/template
    container_name: microservice-template
    environment:
      - DB_HOSTNAME=192.168.6.13
      - DB_PORT=27017
      - DB_USERNAME=admin
      - DB_PASSWORD=pass
    networks:
      metrics_internal:
        ipv4_address: 192.168.6.11
    ports:
      - "8888:8888"
      - "9090:9090"
    deploy:
      mode: host

networks:
  metrics_internal:
    ipam:
      driver: default
      config:
        - subnet: "192.168.6.0/24"
